(async function(){
  const o = {};
  const T = (k, f) => { try { const v = f(); o[k] = v === undefined ? 'undef' : v; } catch (e) { o[k] = 'THROWS ' + e.message; } };
  T('ua', () => navigator.userAgent);
  T('platform', () => navigator.platform); T('vendor', () => navigator.vendor); T('appVersion', () => navigator.appVersion);
  T('webdriver', () => navigator.webdriver); T('languages', () => JSON.stringify(navigator.languages)); T('language', () => navigator.language);
  T('hwc', () => navigator.hardwareConcurrency); T('devMem', () => navigator.deviceMemory); T('maxTouch', () => navigator.maxTouchPoints);
  T('plugins', () => navigator.plugins.length + ':' + Array.from(navigator.plugins).map(p => p.name).join(',')); T('mimeTypes', () => navigator.mimeTypes.length);
  T('pdfViewer', () => navigator.pdfViewerEnabled); T('cookieEnabled', () => navigator.cookieEnabled);
  T('navKeysOwn', () => Object.keys(navigator).length);
  T('navProtoKeys', () => Object.getOwnPropertyNames(Navigator.prototype).length);
  T('navProtoOrder', () => Object.getOwnPropertyNames(Navigator.prototype).slice(0, 30).join(','));
  T('navProtoMissing', () => ['vendorSub','productSub','vendor','maxTouchPoints','scheduling','userActivation','geolocation','doNotTrack','connection','plugins','mimeTypes','pdfViewerEnabled','webkitTemporaryStorage','webkitPersistentStorage','windowControlsOverlay','hardwareConcurrency','cookieEnabled','appCodeName','appName','appVersion','platform','product','userAgent','language','languages','onLine','webdriver','protectedAudience','storageBuckets','clipboard','credentials','keyboard','managed','mediaDevices','storage','serviceWorker','virtualKeyboard','wakeLock','deviceMemory','userAgentData','login','ink','mediaCapabilities','devicePosture','hid','locks','gpu','mediaSession','permissions','presentation','serial','usb','xr','sendBeacon','getBattery','getGamepads','javaEnabled','vibrate','requestMIDIAccess','canShare','share','requestMediaKeySystemAccess','getUserMedia','webkitGetUserMedia'].filter(k => !(k in navigator)).join(','));
  T('uaData', () => navigator.userAgentData ? JSON.stringify({ b: navigator.userAgentData.brands, m: navigator.userAgentData.mobile, p: navigator.userAgentData.platform }) : 'none');
  try { o.uaHigh = navigator.userAgentData ? JSON.stringify(await navigator.userAgentData.getHighEntropyValues(['architecture','bitness','model','platformVersion','uaFullVersion','fullVersionList','wow64'])) : 'none'; } catch (e) { o.uaHigh = 'THROWS ' + e.message; }
  T('connection', () => navigator.connection ? JSON.stringify({ e: navigator.connection.effectiveType, d: navigator.connection.downlink, r: navigator.connection.rtt, s: navigator.connection.saveData }) : 'none');
  T('chrome', () => typeof window.chrome + ':' + (window.chrome ? Object.keys(window.chrome).join(',') : ''));
  T('screen', () => [screen.width, screen.height, screen.availWidth, screen.availHeight, screen.colorDepth, screen.pixelDepth, screen.orientation && screen.orientation.type, screen.availLeft, screen.availTop, screen.isExtended].join('|'));
  T('win', () => [innerWidth, innerHeight, outerWidth, outerHeight, devicePixelRatio, screenX, screenY, screenLeft, screenTop, visualViewport && visualViewport.width, visualViewport && visualViewport.scale].join('|'));
  T('notif', () => typeof Notification + ':' + (typeof Notification !== 'undefined' ? Notification.permission : ''));
  try { const r = await navigator.permissions.query({ name: 'notifications' }); o.permQuery = r.state; } catch (e) { o.permQuery = 'THROWS ' + e.message; }
  T('errStack', () => new Error('x').stack.split('\n').slice(0, 3).join(' // '));
  T('errStackFn', () => { function foo() { return new Error('y').stack.split('\n')[1]; } return foo(); });
  T('nativeToString', () => [Function.prototype.toString.call(Function.prototype.toString), Function.prototype.toString.call(Math.max), Function.prototype.toString.call(document.createElement), Function.prototype.toString.call(Object.getOwnPropertyDescriptor(Navigator.prototype, 'userAgent').get), Function.prototype.toString.call(window.fetch), Function.prototype.toString.call(HTMLCanvasElement.prototype.getContext), Function.prototype.toString.call(Element.prototype.attachShadow)].join(' | '));
  T('navUAdesc', () => JSON.stringify(Object.getOwnPropertyDescriptor(Navigator.prototype, 'userAgent'), (k, v) => typeof v === 'function' ? 'fn:' + v.name : v));
  T('winProtoTag', () => Object.prototype.toString.call(window) + '|' + Object.prototype.toString.call(navigator) + '|' + Object.prototype.toString.call(screen) + '|' + Object.prototype.toString.call(document) + '|' + Object.prototype.toString.call(performance));
  T('winKeys', () => Object.getOwnPropertyNames(window).length);
  T('canvas2d', () => { const c = document.createElement('canvas'); c.width = 200; c.height = 50; const x = c.getContext('2d'); x.textBaseline = 'top'; x.font = '14px Arial'; x.fillStyle = '#f60'; x.fillRect(125, 1, 62, 20); x.fillStyle = '#069'; x.fillText('Cwm fjordbank glyphs vext quiz, 😃', 2, 15); const d = c.toDataURL(); let h = 0; for (let i = 0; i < d.length; i++) h = (h * 31 + d.charCodeAt(i)) | 0; return d.length + ':' + h + ':' + x.measureText('Hello').width; });
  T('measureText', () => { const c = document.createElement('canvas').getContext('2d'); c.font = '16px serif'; const m = c.measureText('mmmmmmmmmmlli'); return [m.width, m.actualBoundingBoxAscent, m.actualBoundingBoxDescent, m.fontBoundingBoxAscent, m.fontBoundingBoxDescent].join('|'); });
  T('webgl', () => { const c = document.createElement('canvas'); const g = c.getContext('webgl'); return g ? 'ctx' : String(g); });
  T('webgl2', () => { const c = document.createElement('canvas'); const g = c.getContext('webgl2'); return g ? 'ctx' : String(g); });
  T('offscreen', () => typeof OffscreenCanvas);
  T('audio', () => typeof AudioContext + '/' + typeof OfflineAudioContext + '/' + typeof webkitAudioContext);
  T('rtc', () => typeof RTCPeerConnection);
  T('speech', () => typeof speechSynthesis + (typeof speechSynthesis !== 'undefined' ? ':' + speechSynthesis.getVoices().length : ''));
  T('mediaDevices', () => typeof navigator.mediaDevices);
  T('battery', () => typeof navigator.getBattery);
  T('trustedTypes', () => typeof window.trustedTypes);
  T('idb', () => typeof indexedDB + '/' + typeof caches + '/' + typeof localStorage + '/' + typeof sessionStorage);
  T('cryptoSubtle', () => typeof crypto.subtle + ':' + typeof crypto.randomUUID);
  T('tz', () => Intl.DateTimeFormat().resolvedOptions().timeZone + '|' + new Date().getTimezoneOffset() + '|' + Intl.DateTimeFormat().resolvedOptions().locale);
  T('intl', () => [typeof Intl.DisplayNames, typeof Intl.ListFormat, typeof Intl.RelativeTimeFormat, typeof Intl.PluralRules, typeof Intl.Segmenter, typeof Intl.supportedValuesOf].join(','));
  T('perf', () => [typeof performance.now(), typeof performance.timeOrigin, typeof performance.memory, performance.memory && typeof performance.memory.jsHeapSizeLimit, typeof performance.getEntriesByType, performance.timing && typeof performance.timing.navigationStart].join('|'));
  T('perfResTiming', () => { const e = performance.getEntriesByType('navigation')[0]; return e ? Object.keys(e.toJSON()).length : 'none'; });
  T('fonts', () => typeof document.fonts + ':' + (document.fonts ? document.fonts.size + ':' + document.fonts.check('12px Arial') + ':' + typeof document.fonts.ready : ''));
  T('matchMedia', () => ['(prefers-color-scheme: dark)','(hover: hover)','(pointer: fine)','(any-pointer: fine)','(prefers-reduced-motion: reduce)','(color-gamut: srgb)','(color-gamut: p3)','(dynamic-range: high)','(forced-colors: active)','(display-mode: browser)','(resolution: 1dppx)','(min-resolution: 2dppx)'].map(q => +matchMedia(q).matches).join(''));
  T('cssSupports', () => [CSS.supports('display', 'grid'), CSS.supports('container-type', 'size'), CSS.supports('selector(:has(a))'), CSS.supports('color', 'color-mix(in srgb, red, blue)'), CSS.supports('aspect-ratio', '1/1'), CSS.supports('accent-color', 'red'), CSS.supports('backdrop-filter', 'blur(1px)'), CSS.supports('text-wrap', 'balance')].map(Number).join(''));
  T('canPlay', () => { const v = document.createElement('video'); const a = document.createElement('audio'); return [v.canPlayType('video/mp4; codecs="avc1.42E01E"'), v.canPlayType('video/webm; codecs="vp9"'), a.canPlayType('audio/mpeg'), a.canPlayType('audio/ogg; codecs="vorbis"'), a.canPlayType('audio/mp4; codecs="mp4a.40.2"')].join('|'); });
  T('mediaSource', () => typeof MediaSource + ':' + (typeof MediaSource !== 'undefined' && MediaSource.isTypeSupported ? MediaSource.isTypeSupported('video/mp4; codecs="avc1.42E01E"') : ''));
  T('svgBBox', () => { const s = document.createElementNS('http://www.w3.org/2000/svg', 'svg'); const t = document.createElementNS('http://www.w3.org/2000/svg', 'text'); t.textContent = 'Hello world'; t.setAttribute('x', '32'); t.setAttribute('y', '32'); s.appendChild(t); document.body.appendChild(s); const b = t.getBBox(); return [b.x, b.y, b.width, b.height, t.getComputedTextLength()].join('|'); });
  T('elemMetrics', () => { const d = document.createElement('div'); d.style.cssText = 'position:absolute;left:0;top:0;font:16px Arial'; d.textContent = 'mmmmmmmmmmlli'; document.body.appendChild(d); const r = d.getBoundingClientRect(); const s = d.style; return [r.width, r.height, d.offsetWidth, d.offsetHeight, getComputedStyle(d).fontFamily].join('|'); });
  T('fontWidths', () => { const out = []; for (const f of ['serif','sans-serif','monospace','Arial','Times New Roman','Courier New','Segoe UI','Helvetica','Verdana','Georgia']) { const d = document.createElement('span'); d.style.cssText = 'position:absolute;font-size:72px;font-family:' + f + ',monospace'; d.textContent = 'mmmmmmmmmmlli'; document.body.appendChild(d); out.push(Math.round(d.getBoundingClientRect().width)); } return out.join(','); });
  T('docProps', () => [document.readyState, document.hidden, document.visibilityState, document.hasFocus(), document.characterSet, document.compatMode, document.designMode, typeof document.fonts, typeof document.timeline, document.referrer === ''].join('|'));
  T('worker', () => typeof Worker + '/' + typeof SharedWorker + '/' + typeof Blob + '/' + typeof URL.createObjectURL);
  T('blobWorker', () => { try { const w = new Worker(URL.createObjectURL(new Blob(['postMessage(1)'], { type: 'application/javascript' }))); w.terminate(); return 'ok'; } catch (e) { return 'THROWS ' + e.message; } });
  T('wasm', () => typeof WebAssembly + ':' + (typeof WebAssembly !== 'undefined' ? typeof WebAssembly.instantiate : ''));
  T('storageEst', () => typeof navigator.storage + ':' + (navigator.storage ? typeof navigator.storage.estimate : ''));
  T('touch', () => 'ontouchstart' in window);
  T('gamepads', () => typeof navigator.getGamepads);
  T('doc.all', () => typeof document.all);
  T('sendBeacon', () => typeof navigator.sendBeacon);
  T('shadow', () => { const h = document.createElement('div'); document.body.appendChild(h); const sr = h.attachShadow({ mode: 'closed' }); const k = document.createElement('span'); h.appendChild(k); return [k.isConnected, k.parentNode === h, h.childNodes.length].join('|'); });
  T('shadowBody', () => { const f = document.createElement('iframe'); document.body.appendChild(f); const d = f.contentDocument; if (!d) return 'nodoc'; d.body.attachShadow({ mode: 'closed' }); const k = d.createElement('div'); d.body.appendChild(k); return [k.isConnected, k.parentNode === d.body, d.body.childNodes.length].join('|'); });
  T('crossAdopt', () => { const f = document.createElement('iframe'); document.body.appendChild(f); const d = f.contentDocument; const p = document.createElement('div'); d.body.appendChild(p); return [p.parentNode === d.body, p.ownerDocument === d, d.body.firstChild === p].join('|'); });
  T('iframeBlank', () => { const f = document.createElement('iframe'); document.body.appendChild(f); return [f.contentWindow.location.href, f.contentDocument.readyState, f.contentDocument.URL].join('|'); });
  T('srcdocIframe', () => { const f = document.createElement('iframe'); f.srcdoc = '<p>x</p>'; document.body.appendChild(f); return [f.contentWindow ? 'win' : 'nowin', f.contentDocument ? f.contentDocument.readyState : 'nodoc'].join('|'); });
  o.__ = 'done';
  return JSON.stringify(o);
})()
