[package]
name = "app"
version.workspace = true
edition.workspace = true

[[bin]]
name = "browser"
path = "src/main.rs"

[dependencies]
browser = { path = "../crates/browser" }
engine = { path = "../crates/engine" }
common = { path = "../crates/common" }
env_logger = { version = "0.11", default-features = false, features = ["auto-color"] }
